In [1]:
import pandas as pd

In [2]:
source = 'https://data.culture.gouv.fr/api/explore/v2.1/catalog/datasets/aides-a-la-presse-classement-des-titres-de-presse-aides/exports/csv?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B'

In [3]:
aides = (
    pd
    .read_csv(source, sep=';')
)

aides

,Bénéficiaires,Aides directes (1) (en €),Dont aides au pluralisme (Aides directes) (en €),Dont aide au pluralisme des titres ultra-marins (Aides directes) (en €),Dont aide au portage (Aides directes) (en €),Dont FSDP (Aides directes) (en €),Dont FSEIP (aides directes) (en €),Aide filière \n(aide à la distribution) (2) (en €),Aide à la modernisation sociale (3) (en €),Aide exceptionnelle au bénéfice de certains éditeurs de presse (4) (en €),Aide exceptionnelle au bénéfice des titres de presse ultra-marins (5) (en €),Total des aides individuelles (1) + (2) + (3) + (4) + (5) (en €),Diffusion annuelle (en exemplaires),Aide par exemplaire (en €),Groupes ou sociétés de presse d'appartenance,Année
0,L'HUMANITE,3321775.0,3079884.0,NaN,241891.0,NaN,NaN,269100.0,NaN,NaN,NaN,3590875,9846064.0,0.364702,NaN,2015
1,LE PARISIEN,959736.0,NaN,NaN,959736.0,NaN,NaN,NaN,613205.0,NaN,NaN,1572941,76199884.0,0.020642,NaN,2015
2,PRESSE OCEAN,1341811.0,236075.0,NaN,1105736.0,NaN,NaN,NaN,NaN,NaN,NaN,1341811,10700003.0,0.125403,NaN,2015
3,LA VOIX DU NORD,664515.0,NaN,NaN,506515.0,158000.0,NaN,NaN,366260.0,NaN,NaN,1030775,79681693.0,0.012936,NaN,2015
4,CENTRE PRESSE AVEYRON,590092.0,84000.0,NaN,506092.0,NaN,NaN,NaN,NaN,NaN,NaN,590092,5949333.0,0.099186,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2755,LA VOIX DE L'AIN,9861.0,9861.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9861,623763.0,0.015809,SOGEMEDIA,2021
2756,LA VOIX DU MIDI - Toutes éditions,2534.0,2534.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2534,NaN,NaN,SIPA OUEST France,2021
2757,VSD,121853.0,121853.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121853,NaN,NaN,GHOSN CAPITAL (VSD),2021
2758,worldcrunch.com,149999.0,NaN,NaN,NaN,149999.0,NaN,NaN,NaN,NaN,NaN,149999,NaN,NaN,NaN,2021
2759,zoolemag.com,94236.0,NaN,NaN,NaN,94236.0,NaN,NaN,NaN,NaN,NaN,94236,NaN,NaN,NaN,2021

In [4]:
(
    aides
    .pivot_table(
        index='Bénéficiaires',
        columns = 'Année',
        values = 'Aides directes (1) (en €)'
    )
    .assign(
        total = lambda df: df.sum(axis=1)
    )
    .sort_values('total', ascending = False)
    .head(50)
    .style
    .format(thousands = " ", na_rep='', precision = 0)
)